### ISSUE TITLE
Project planning

### ISSUE THREAD

**Issue by Duveshka** [SoftwareCountry/arcadia-parties#1]
Start discussion)

**Comment by laska-sl** [comment]
API: Define authentication, create AuthController

**Comment by Duveshka** [comment]
API: Create models for DB, connect DB to our project for start development

**Comment by Duveshka** [comment]
API: Create Controller for Staff. Get information about it and work with this infromation.

**Comment by laska-sl** [comment]
API: Create DTOs for controllers

**Comment by Duveshka** [comment]
SPA: Create Start Component with authorization or registration

**Comment by Duveshka** [comment]
SPA: Create component with party calendar

**Comment by laska-sl** [comment]
SPA: Create SignIn component

**Comment by Duveshka** [comment]
SPA: Add NgRx

**Comment by Duveshka** [comment]
> SPA: Create component with party calendar

Display information in the calendar

**Comment by sponkrashin** [comment]
> API: Create models for DB, connect DB to our project for start development

I'd have two separate issues, one for setting all db stuff up and the other for database models.

**Comment by sponkrashin** [comment]
Along with prefixes in issue title let's use Issue Labels.

**Comment by sponkrashin** [comment]
To be able to develop SPA components in parallel with API and to not wait until API controllers are ready, I'd make two issues for each frontend component: the first one for creating component itself with some mock data, and the second one for intergration with API.

**Comment by sponkrashin** [comment]
The same thing is for API: one issue about controller with mock data and the other for loading real data from the database or somewhere else.

**Comment by sponkrashin** [comment]
Also, mark some issues with "initial" or "setup" label to specify issues that should been done in prior of any other.

**Comment by sponkrashin** [comment]
For SPA it is NgRx, application layout, main design, for API it is integration and configuration of any external libraries, logging, database.
